### PR TITLE
Tools #2 - DawidMalarz

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by jakjan95 — APPROVED** [review]
good job all done correct :)

**Review by DamiXioR — COMMENTED** [review]
nice work, just remove redundant comments

**Comment by ghost** [comment]
@DamiXioR  Good point! I removed these comments 👍

**Review by Marcinati — APPROVED** [review]
Everything looks good.

**Comment by ziobron** [comment]
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

**Pull request closed without merging**
