### PR TITLE
Homework Narzędzia #2

### PR DESCRIPTION
**Pull request by mariomoore**

### CODE REVIEW

**Review by Marcinati — CHANGES_REQUESTED** [review]
You deleted min function. The task was to add implementation of reverse function without removing any program functionality.

**Comment by mariomoore** [comment]
> You deleted min function. The task was to add implementation of reverse function without removing any program functionality.

I misunderstood the instructions. I changed it. Thank you @Marcinati

**Review by Marcinati — APPROVED** [review]
Now everything looks good. :)

**Review by DamiXioR — COMMENTED** [review]
looks good

**Comment by ziobron** [comment]
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

**Pull request closed without merging**
