### PR TITLE
Homework Tools #2

### PR DESCRIPTION
**Pull request by DamiXioR**

### CODE REVIEW

**Review by Kasperice — COMMENTED** [review]
Changes look good. Was the `README.txt` file necessary?

**Comment by DamiXioR** [comment]
> Changes look good. Was the `README.txt` file necessary?

yes, to explain :)

**Comment by DamiXioR** [comment]
in README.txt I explained that I made some changes before, with commit "conflicts resolve done"

**Comment by ziobron** [comment]
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

**Pull request closed without merging**
