### PR TITLE
homework

### PR DESCRIPTION
**Pull request by kyrtaq**
i hope i did everything okay

### CODE REVIEW

**Review by Kasperice — CHANGES_REQUESTED** [review]
I think you missed something. You do not have src/main.cpp, inc/functions.hpp and Makefile files. Please check one more time

**Comment by Kasperice** [comment]
> I think you missed something. You do not have src/main.cpp, inc/functions.hpp and Makefile files. Please check one more time

I think that something went wrong with cherry-pick, because I see that previous commits seems good. It started going wrong direction during cf7597a and later

**Comment by kyrtaq** [comment]
> I think you missed something. You do not have src/main.cpp, inc/functions.hpp and Makefile files. Please check one more time

yeah, now i see that i added to many things to my merge, do you know how do i un-merge or something?

**Comment by kyrtaq** [comment]
> > I think you missed something. You do not have src/main.cpp, inc/functions.hpp and Makefile files. Please check one more time
> 
> I think that something went wrong with cherry-pick, because I see that previous commits seems good. It started going wrong direction during [cf7597a](https://github.com/coders-school/resolvable-conflict/commit/cf7597a9e8976d443676f30ab9a8592353efbe99) and later

is it because i added the changes?

**Comment by Kasperice** [comment]
> > I think you missed something. You do not have src/main.cpp, inc/functions.hpp and Makefile files. Please check one more time
> 
> yeah, now i see that i added to many things to my merge, do you know how do i un-merge or something?

Everything worked on f6d09a4, so you can try `git reset f6d09a4 --hard` then you will lose later changes, or without `--hard` to get those changes staged. I think it will be easier to lose those later files.

**Comment by kyrtaq** [comment]
i`ve made another pull request and everything should be fine there, thanks

**Pull request closed without merging**
