### PR TITLE
homework 2

### PR DESCRIPTION
**Pull request by kyrtaq**
now it should be alright..

### CODE REVIEW

**Review by Kasperice — APPROVED** [review]
Looks much better now :) Remember about empty lines at the end of file

**Comment by niemarcin** [comment]
I'm not sure, but for me it looks like you don't have "Git-cherrypick" part of homework. I have not found any track of "vimtutor" branch, merging this "vimtutor" branch to master, nor the cherry-picked commit with vimtutor.

I refer to the graph shown on our edu platform, where tutor commit is visible twice. [https://coders.school/edu/wp-content/uploads/2020/05/Zrzut-ekranu-2020-05-31-o-00.09.59.png](url)

**Comment by kyrtaq** [comment]
> I'm not sure, but for me it looks like you don't have "Git-cherrypick" part of homework. I have not found any track of "vimtutor" branch, merging this "vimtutor" branch to master, nor the cherry-picked commit with vimtutor.
> 
> I refer to the graph shown on our edu platform, where tutor commit is visible twice. [https://coders.school/edu/wp-content/uploads/2020/05/Zrzut-ekranu-2020-05-31-o-00.09.59.png](url)

Screenshot from 2020-05-31 23-17-22

weird, because on my local repo there is the vimtutor branch and i merged it before

**Comment by kyrtaq** [comment]
Okay, I`ve merged it once again just in case

**Review by niemarcin — APPROVED** [review]

**Comment by ziobron** [comment]
+4 XP Narzędzia#2 – vimtutor
+5 XP Narzędzia#2 – git - konflikty
+4 XP Narzędzia#2 – flagi kompilacji
+3 XP Narzędzia#2 – git - cherrypick
+8 XP delivery before 07.06.2020

{ "requirement_ids": [1119, 1999, 1119, 2000, 1119, 2001, 1119, 2002], "points": [2, 4, 2, 5, 2, 4, 2, 3] }

**Pull request closed without merging**
